from re import I
import sys
import os

myDir = os.getcwd()
sys.path.append(myDir)

from controllers.Mesero.PedidosController import PrincipalController
from Views.Mesero.CreatePedido import Ui_CreatePedido
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pedido(object):

    def __init__(self):
        self.pedidoController = PrincipalController(self)

    def setupUi(self, Pedido):
        Pedido.setObjectName("Pedido")
        Pedido.resize(1012, 727)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/image_Emp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pedido.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Pedido)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 931, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.table_pedidos = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_pedidos.setRowCount(10)
        self.table_pedidos.setObjectName("table_pedidos")
        self.table_pedidos.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pedidos.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.table_pedidos, 1, 0, 1, 4)
        self.btn_list = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_list.setFont(font)
        self.btn_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_list.setObjectName("btn_list")
        self.gridLayout.addWidget(self.btn_list, 2, 0, 1, 1)
        self.btn_create = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create.setFont(font)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setObjectName("btn_create")
        self.gridLayout.addWidget(self.btn_create, 2, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        Pedido.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Pedido)
        self.statusbar.setObjectName("statusbar")
        Pedido.setStatusBar(self.statusbar)

        self.retranslateUi(Pedido)
        QtCore.QMetaObject.connectSlotsByName(Pedido)

        self.l = self.btn_list.clicked.connect(lambda:self.pedidoController.listPedidos())
        self.c = self.btn_create.clicked.connect(lambda:self.pedidoController.openCreate(Ui_CreatePedido))

    def retranslateUi(self, Pedido):
        _translate = QtCore.QCoreApplication.translate
        Pedido.setWindowTitle(_translate("Pedido", "Foud Court"))
        item = self.table_pedidos.horizontalHeaderItem(0)
        item.setText(_translate("Pedido", "ID Pedido"))
        item = self.table_pedidos.horizontalHeaderItem(1)
        item.setText(_translate("Pedido", "ID Negocio"))
        item = self.table_pedidos.horizontalHeaderItem(2)
        item.setText(_translate("Pedido", "Mesero"))
        item = self.table_pedidos.horizontalHeaderItem(3)
        item.setText(_translate("Pedido", "Mesa"))
        item = self.table_pedidos.horizontalHeaderItem(4)
        item.setText(_translate("Pedido", "Producto"))
        item = self.table_pedidos.horizontalHeaderItem(5)
        item.setText(_translate("Pedido", "Cantidad")) ,
        item = self.table_pedidos.horizontalHeaderItem(6)
        item.setText(_translate("Pedido", "Valor"))
        item = self.table_pedidos.horizontalHeaderItem(7)
        item.setText(_translate("Pedido", "Estado"))
        item = self.table_pedidos.horizontalHeaderItem(8)
        item.setText(_translate("Pedido", "Fecha"))
        self.btn_list.setText(_translate("Pedido", "Listar"))
        self.btn_create.setText(_translate("Pedido", "Crear"))
        self.label.setText(_translate("Pedido", "Ventana Pedido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pedido = QtWidgets.QMainWindow()
    ui = Ui_Pedido()
    ui.setupUi(Pedido)
    Pedido.show()
    sys.exit(app.exec_())
