import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)


from controllers.Cocinero.cocinerocontrollers import Actualizarlistascontrollers
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cocinero(object):

    def __init__(self):
        self.Actualizarlistascontrollers = Actualizarlistascontrollers(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1044, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/image_Emp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table_segunda = QtWidgets.QTableWidget(self.centralwidget)
        self.table_segunda.setGeometry(QtCore.QRect(530, 150, 471, 391))
        self.table_segunda.setObjectName("table_segunda")
        self.table_segunda.setColumnCount(3)
        self.table_segunda.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_segunda.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segunda.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segunda.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_segunda.setHorizontalHeaderItem(2, item)
        self.table_primera = QtWidgets.QTableWidget(self.centralwidget)
        self.table_primera.setGeometry(QtCore.QRect(41, 147, 471, 391))
        self.table_primera.setObjectName("table_primera")
        self.table_primera.setColumnCount(3)
        self.table_primera.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.table_primera.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_primera.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_primera.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_primera.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(41, 108, 265, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(540, 110, 194, 33))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(482, 550, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.btn_listo = QtWidgets.QPushButton(self.centralwidget)
        self.btn_listo.setGeometry(QtCore.QRect(710, 550, 115, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_listo.setFont(font)
        self.btn_listo.setObjectName("btn_listo")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(100, 550, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_rechazar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rechazar.setGeometry(QtCore.QRect(280, 550, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_rechazar.setFont(font)
        self.btn_rechazar.setObjectName("btn_rechazar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(513, 108, 16, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 20, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(450, 540, 20, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(570, 540, 16, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #--------------------Events--------------------------------------
        self.l = self.pushButton.clicked.connect(lambda:self.Actualizarlistascontrollers.listPedidos())
        self.l = self.pushButton.clicked.connect(lambda:self.Actualizarlistascontrollers.listpendientes())
        self.l = self.btn_aceptar.clicked.connect(lambda:self.Actualizarlistascontrollers.pedidoaceptado())
        self.l = self.btn_rechazar.clicked.connect(lambda:self.Actualizarlistascontrollers.pedidocancelar())
        self.t = self.btn_listo.clicked.connect(lambda:self.Actualizarlistascontrollers.pedidolisto())
        #--------------------End Events---------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Foud Court"))
        item = self.table_segunda.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_segunda.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID_pedido"))
        item = self.table_segunda.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.table_segunda.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cantidad"))
        item = self.table_primera.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_primera.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID_pedido"))
        item = self.table_primera.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.table_primera.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cantidad"))
        self.label.setText(_translate("MainWindow", "Pedidos Pendientes"))
        self.label_2.setText(_translate("MainWindow", "Pedidos Listos"))
        self.pushButton.setText(_translate("MainWindow", "Listar "))
        self.btn_listo.setText(_translate("MainWindow", "Pedido Listo"))
        self.btn_aceptar.setText(_translate("MainWindow", "Aceptar Pedido"))
        self.btn_rechazar.setText(_translate("MainWindow", "Rechazar Pedido"))
        self.label_3.setText(_translate("MainWindow", "COCINERO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cocinero = QtWidgets.QMainWindow()
    Ui = Ui_cocinero()
    Ui.setupUi(cocinero)
    cocinero.show()
    sys.exit(app.exec_())
